### ISSUE TITLE
Transfer documentation from README.md to the collections

### ISSUE THREAD

**Issue by peterramsing** [lostgrid/lostgrid-site#12]
I created a collection for all the docs to be created in. They are then looped through. I'm creating an example within #11 for the Lost Column but we'll need to transfer all of them over in time.

**Comment by peterramsing** [comment]
Note to self for sorting: https://github.com/jekyll/jekyll/issues/2515#issuecomment-46107601

**Comment by japick** [comment]
How is this going? :)

**Comment by peterramsing** [comment]
@japick Now that I'm doing contract work only I'm not working 60 hour weeks...so I have time for this now! I'm reserving a portion of Wednesdays to Lost. 👍🏻

**Comment by peterramsing** [comment]
Woo. This is done, now.

**Comment by japick** [comment]
Ok, great. I'll pull tonight/tomorrow when I get a chance and will tweak any necessary bits of the design. We should also add a list of sites using Lost (if you've not done already).
