### ISSUE TITLE
Add visuals to docs

### ISSUE THREAD

**Issue by peterramsing** [lostgrid/lostgrid-site#19]
From @nirfse in library's repo:

Please consider adding screenshots or visual representation of grid layouts in documentation. There are horizontal, vertical, waffles, and masonry grid layouts available to day.

While "horizontal' and "vertical" grids meet the expectations of an accidentally passing by beginner or non front-end developer, it's absolutely not obvious what "waffles" or "masonry" grids look like. I had to double-check in google, what exactly is meant by these. But even googling wasn't straightforward with clarification.

**Comment by peterramsing** [comment]
@nirfse There is the old gh-pages that should really be transferred to here. Thanks for bringing this up. The page lacks labels but might be a good starting point.

(Old page: http://peter.coffee/lost/)

**Comment by joedooley** [comment]
I found a series of lostgrid video tutorials that go over each of the different grids. It was really good! Linking to these would make lostgrid even easier to learn for anyone new to lost.
[https://youtu.be/xTcOUh4rKMo?list=PLLnpHn493BHFvjZzyYrQP0RTsG-Al7j9m](url)

**Comment by peterramsing** [comment]
There is now an example. This is done. 👍
