### ISSUE TITLE
Sitemap + content

### ISSUE THREAD

**Issue by japick** [lostgrid/lostgrid-site#2]
I know this will likely be an iterative process, but we could do with defining an initial sitemap (w/ content for each section) that we can tweak and add to in future.

**Comment by peterramsing** [comment]
Presently thinking the following pages:

Home
- Docs
- About

Super simple to start. Working on copy for all three. Will link to ~~Google Doc~~ Gists here.

**Comment by peterramsing** [comment]
Here's a list for the docs:
https://gist.github.com/peterramsing/7000138a6ee6d4233f01dac0ff4258e3

**Comment by peterramsing** [comment]
About copy. I keep thinking that I should write more but I'm not sure what else to add. This is the first pass but I think it'll probably be as simple as this:
https://gist.github.com/peterramsing/2b9180d2f50559c0225ab5625f14d6b3

**Comment by peterramsing** [comment]
Homepage: @japick I like it as simple as you sent in the demo. We just need a little spot for "about" ...although I'm not opposed to putting the about within the homepage. 👍

**Comment by thinklab-team** [comment]
I think we could just go with 'Docs' for now and encompass 'About' within the Introduction section. What do you think?

**Comment by japick** [comment]
I think we could just go with 'Docs' for now and encompass the 'About' content into the Introduction section. We can always add a dedicated about page at a later stage. 

What do you think?

**Comment by peterramsing** [comment]
@japick Sounds good!

**Comment by japick** [comment]
Did you setup Jekyll on a repo yet? If not, I can just set it up locally and whack it onto a repo, if it makes things easier?

**Comment by peterramsing** [comment]
If you haven't I can. I was going to get started on that today tomorrow after I create issues based on the email that we can assign. 👍

**Comment by japick** [comment]
Ok, I'll do it :)

**Comment by peterramsing** [comment]
@japick I have been looking at the analytics and it looks like a huge amount of people go to the "installation" wiki.

It doesn't need to be in the V1 but something to think about for V2.
