### ISSUE TITLE
Colour Contrast Issue

### ISSUE THREAD

**Issue by thisispaul** [lostgrid/lostgrid-site#20]
I just been reading your docs and found it quite difficult to read some things.

You have some colour contrast issues which make your example code difficult to read (you can check them here http://webaim.org/resources/contrastchecker/).

I have listed the worst offenders below, there are some others but these three examples are very difficult to read.

![image](https://cloud.githubusercontent.com/assets/1013975/21852425/e1d1b60c-d80a-11e6-95d8-cdd8b89eb8ee.png)
```
.row, .quarter, .half
foreground: #bb0066
background: #434243
contrast: 1.57:1
```

![image](https://cloud.githubusercontent.com/assets/1013975/21852511/3b10bae2-d80b-11e6-9e72-d39228daceb2.png)
```
:first-child
foreground: #555555
background: #434243
contrast: 1.34:1
```

![image](https://cloud.githubusercontent.com/assets/1013975/21852554/78459c20-d80b-11e6-8074-b19ba0535f92.png)
```
width, height
foreground: #336699
background: #434243
contrast: 1.67:1
```

**Comment by japick** [comment]
See latest pull request.

**Comment by peterramsing** [comment]
@japick Thanks for tackling this!
