### ISSUE TITLE
Show the style syntax on the examples page

### ISSUE THREAD

**Issue by allanesquina** [lostgrid/lostgrid-site#24]
Hi guys, I've started learning *Lostgrid* recently by reading the docs and I realized I can't see the syntax code on the examples page which could be a good feature to improve the learning curve. What do you think? 

Best :+1:

**Comment by peterramsing** [comment]
@japick, I can own this one.

**Comment by peterramsing** [comment]
It's coming along.

![screen shot 2017-03-18 at 13 56 32](https://cloud.githubusercontent.com/assets/3523268/24075927/ccfbbf78-0be2-11e7-994b-1301a5983311.jpg)

**Comment by peterramsing** [comment]
🎉 http://lostgrid.org/lostgrid-example.html

**Comment by allanesquina** [comment]
Perfect! 
Thanks a lot @peterramsing :+1:
