### ISSUE TITLE
Chrome detecting language of page as "Latin".

### ISSUE THREAD

**Issue by shahzeb1** [lostgrid/lostgrid-site#25]
![lostgrid](https://cloud.githubusercontent.com/assets/1383831/24635556/d48864e6-1888-11e7-9dad-c02b6f13394c.png)

I believe this is something I might be able to fix.

**Comment by peterramsing** [comment]
@shahzeb1 Merged. Thanks!

**Comment by shahzeb1** [comment]
Checked on the live website, is fixed now! 😃
