### ISSUE TITLE
Back-end platform

### ISSUE THREAD

**Issue by japick** [lostgrid/lostgrid-site#3]
I was thinking WordPress would be most suitable for the site's back-end - unless you had a preference already? I work with WP on a daily basis, so I'm more than comfortable using it. 

What were your thoughts on this?

**Comment by peterramsing** [comment]
I don't work with Wordpress other than to fix things on my wife's site. I was leaning towards a static site as I don't think I'm ready to dive fully into WP.

With something static it opens up the opportunity for more developers to contribute now and in the future.

I've been using [Nunjucks](https://mozilla.github.io/nunjucks/) from Mozilla (although not totally a static-site, it templates well) and am certainly not opposed to [Jekyll](https://jekyllrb.com/). This also makes the site extremely portable!

I'm more than happy to be swayed towards Wordpress or a sort of CMS, though. :smile:

**Comment by thinklab-team** [comment]
Happy to roll with Jekyll (not used Nunjucks). Although, using an open-source CMS like WordPress would, in my opinion, open more doors re future developers, as I'd hedge my bets that more devs use WordPress than a flat file alternative like Jekyll, for example. But then again, going down the 'static' root would be quicker and require less maintenance...

**Comment by japick** [comment]
Happy to roll with Jekyll (not used Nunjucks). Although, using an open-source CMS like WordPress would, in my opinion, open more doors re future developers, as I'd hedge my bets that more devs use WordPress than a flat file alternative like Jekyll, for example. But then again, going down the 'static' root would be quicker and require less maintenance...

**Comment by japick** [comment]
I'm leaning more towards static now!

**Comment by peterramsing** [comment]
I'm totally fine spinning up a droplet for WP or maybe even seeing if we can get [VisualPeople](http://visualpeople.com/) to sponsor a WP instance but I suppose if we can avoid a DB I'd be pretty happy about that. You're right, though–there are a lot of WP devs out there. I am a fan of starting out static, though.

Static for now? Decision time. :smile:

**Comment by japick** [comment]
Yeah lets just go with static for now then!

**Comment by mestaritonttu** [comment]
If considering a CMS, I recommend [ProcessWire](http://processwire.com/). Very refreshing for anyone used to some legacy tentacle-monster-CMSes :)
Good intro article: http://code.tutsplus.com/articles/4-reasons-to-choose-processwire-as-your-next-cms--cms-25062

**Comment by peterramsing** [comment]
For now let's just do static. 👍 

Hosting with GitHub is amazing.
