### ISSUE TITLE
Frontend build

### ISSUE THREAD

**Issue by japick** [lostgrid/lostgrid-site#4]
What are your thoughts on a one-pager? I quite like sites like http://kenwheeler.github.io/slick/ that keep everything on the one page with scroll-to sections. 

My idea behind the initial design was to have a fixed sidebar with the main content on the right scrollable. Each heading and sub index would then scroll to the relevant section on click. Could be quite nice!

**Comment by peterramsing** [comment]
With a fixed sidebar I'm all for it! I've always been a fan of Slick's site. Dare I say...it's "slick" :wink: 

Yes to one-pager sans-docs.

**Comment by peterramsing** [comment]
@japick Do we need this issue anymore?

**Comment by japick** [comment]
@peterramsing nope, don't think so.
