### ISSUE TITLE
Create Initial Jekyll Site

### ISSUE THREAD

**Issue by peterramsing** [lostgrid/lostgrid-site#8]
Create the initial Jekyll setup laying out the structure, etc.
- [x] Initial Jekyll creation/de-boilerplating
- [x] Setup how docs are structured

**Comment by peterramsing** [comment]
The initial site is there. I'm working on laying out the docs now. Instead of doing one big page I'm splitting it up into different pieces for each...at least unless I see a Jekyll setup that works better. 👍 Am planning to have complete by Friday night Pacific Time.

**Comment by peterramsing** [comment]
@japick I didn't clue you into this issue I think. I just saw that you said you'd do this. I hope we didn't double work. I'm just finishing up the template for the docs side of things...

I think my biggest learning from this is even though it's all volunteer and help as we can...it still needs to be organized who's doing what and by when. I'm sorry if I've caused confusion. Hopefully the tickets with assignees help!

**Comment by peterramsing** [comment]
@japick Alright, I got some progress. I found [this](https://github.com/bruth/jekyll-docs-template) by @bruth that was so much better than what I had made. I've mad a lot of modifications and plan to make more my Saturday morning. I want to clean out Bootstrap (I don't dislike it but want to remove it because...well, it is a site for LostGrid. 😄) and then do some refactoring of the layouts, etc. It's still feeling like a WIP.

To what point do you want it before you take over and implement the design?

Luckily with our time-zone splits, I doubt we'll have too many merge conflicts from doing things at the same time.

Since this is WIP, I think that it might work well to submit a PR at the culmination of our day's work for the other to review and merge. I'm not thinking of doing any serious code review but simply to see what the other did and then merge so we can pull master and go at it again. Either branch in this repo or in our forked repo work for now. We can firm up the process later but for now, we can just build.

Alright. Let me know if you have any questions. I want to code more tonight but it's been a tiring week. Phew. 😴

**Comment by japick** [comment]
I didn't get a chance this weekend anyway, so that's cool. We haven't done double work :)

Yeah, we don't need to use Bootstrap for this anyway. 

Sounds good. If you get done whatever you need to do your end and when you're happy with the architecture etc, just share the repo with me and I'll start integrating the design.

**Comment by japick** [comment]
You down with that? :)

**Comment by peterramsing** [comment]
@japick Yessir!

Deadline for myself:
- [x] Complete with all my portion of Jekyll by Thursday night US time (that will give me tonight and tomorrow night to finish up).

**Comment by japick** [comment]
Sorry for the radio silence - been busy of late!

Am I all good to go on the design integration now?

**Comment by peterramsing** [comment]
@japick Yes. I think the foundation should be in place enough. I realize that it might be not quite finished but it felt like a good handoff point. I didn't provide any docs on how it's structured but I feel like it's at least sort of clear.

Let me know if you have any questions and if I need to address anything just ping me.

**Comment by japick** [comment]
Ok, nice one. I'll crack on with it tonight.

**Comment by peterramsing** [comment]
Based on this for the GitHub pages I'm tempted to wrap this into the main LostGrid project. It doesn't really change much as it's just where the code lives. Thoughts?

https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by japick** [comment]
Yeah sounds good to me. Happy with that if you are. 

Btw, I've been super busy this last week, so haven't managed to progress the site much yet. I've cloned the repo and Jekyll is all setup locally. Just need to find some time!

**Comment by peterramsing** [comment]
Let's be honest...are we really ever happy with anything we make. Each time I work on a project I always learn something new so there will always be an evolution...but I think there is at least a foundation.

**Comment by japick** [comment]
Agreed.

**Comment by japick** [comment]
FYI, I should have a good chunk of time over the weekend to progress this.

**Comment by japick** [comment]
Could you give me permission to push to the repo, please? :)

**Comment by peterramsing** [comment]
@japick Whoops. Sorry! You should have it now.
