### ISSUE TITLE
Do initial implementation of design.

### ISSUE THREAD

**Issue by peterramsing** [lostgrid/lostgrid-site#9]

**Comment by peterramsing** [comment]
@japick It's looking super super awesome! Love the updates!

**Comment by japick** [comment]
Yeah, happy with how it's coming on. It's getting there!

**Comment by japick** [comment]
To be honest, I'd say it's at a good stage for you to start creating the pages and dropping in the real content. I can then attend to any styling around that.

**Comment by peterramsing** [comment]
Cool. I'll close this and move onto #12.
